### ISSUE TITLE
"yotta test" error

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/greentea#112]
Hi,

I run test code through _yotta test_, but meet the following error:
```
yotta test mbed-drivers-test-echo
info: generate for target: nu-numbed-nuc472-armcc 1.1.0 at C:\CCLi8\IoT\mbed\beta\nu_mbed_dev\yotta_targets\nu-numbed-nuc472-armcc
WARNING: preprocessing of .S files is not supported by ARMCC on windows.
CMake Warning at C:/CCLi8/IoT/mbed/beta/mbed-drivers-master/yotta_modules/uvisor-lib/source/CMakeLists.txt:44 (message):


           *********************************************************************
           * WARNING (uvisor-lib): unsupported platform; your code will still  *
           *                       work but no security feature is provided;   *
           *                       UVISOR_DISABLED is set by default           *
           *********************************************************************


-- Configuring done
-- Generating done
-- Build files have been written to: C:/CCLi8/IoT/mbed/beta/mbed-drivers-master/build/nu-numbed-nuc472-armcc
ninja: no work to do.
info: using filter "mbedgt --digest stdin -v -V" for tests in C:\CCLi8\IoT\mbed\beta\mbed-drivers-master\build\nu-numbed-nuc472-armcc\test
info: test mbed-drivers: mbed-drivers-test-echo
mbedgt: unexpected error:
        run_host_test() got an unexpected keyword argument 'hooks'
Traceback (most recent call last):
  File "C:\Python27\Scripts\mbedgt-script.py", line 9, in <module>
    load_entry_point('mbed-greentea==0.2.8', 'console_scripts', 'mbedgt')()
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 320, in main
    cli_ret = main_cli(opts, args)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 568, in main_cli
    verbose=opts.verbose_test_result_only)
TypeError: run_host_test() got an unexpected keyword argument 'hooks'
warning: test child has not exited and will be terminated
error: test mbed-drivers-test-echo failed (command: mbed-drivers-test-echo)
info: tests complete: 0 passed, 1 failed

C:\CCLi8\IoT\mbed\beta\mbed-drivers-master>Traceback (most recent call last):
  File "C:\Python27\Scripts\mbedhtrun-script.py", line 9, in <module>
    load_entry_point('mbed-host-tests==0.2.6', 'console_scripts', 'mbedhtrun')()
  File "c:\python27\lib\site-packages\mbed_host_tests\mbedhtrun.py", line 34, in main
    result = test_selector.execute()
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_runner\host_test_default.py", line 302, in execute
    self.logger.prn_inf("copy image onto target...")
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_conn_proxy\conn_proxy_logger.py", line 62, in prn_inf
    self.__prn_log('INF', text, timestamp)
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_conn_proxy\conn_proxy_logger.py", line 50, in __prn_log
    self.__prn_func(s, nl=True)
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_conn_proxy\conn_proxy_logger.py", line 36, in __prn_func
    sys.stdout.flush()
IOError: [Errno 22] Invalid argument
```
My test platform
OS: Windows 7
python: 2.7.11
mbed-greentea (0.2.8)
mbed-host-tests (0.2.6)
mbed-ls (0.2.4)
mbed-test-wrapper (1.0.0)
yotta (0.16.2)

**Comment by PrzemekWirkus** [comment]
Hello @ccli8,
We are not supporting ```yotta test``` command for ```Greentea``` v 0.2.x at the moment.
It's related to changes in our tool stack. Sorry for inconvenience.
Please instead of ```yotta test``` command use in top of your module:

```
$ mbedgt -VS
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2463
