### ISSUE TITLE
TypeError caused by incorrect formatting of error message

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/greentea#134]
https://github.com/ARMmbed/greentea/blob/master/mbed_greentea/mbed_test_api.py#L138

```
mbedgt: mbed-host-test-runner: started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mbed_greentea/mbed_greentea_cli.py", line 401, in run_test_thread
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/mbed_greentea/mbed_test_api.py", line 189, in run_host_test
    p = run_command(cmd)
  File "/usr/local/lib/python2.7/dist-packages/mbed_greentea/mbed_test_api.py", line 139, in run_command
    str(e), e.child_traceback)
TypeError: %d format: a number is required, not str
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2633

**Comment by PrzemekWirkus** [comment]
I will fix it asap!
