### ISSUE TITLE
mbedgt error in listdir

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/greentea#194]
Hi
It seems that greentea can not list any more tests ?

$ mbedgt --list
mbedgt: greentea test automation tool ver. 1.2.2
mbedgt: unexpected error:
        listdir() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "C:\Python27\Scripts\mbedgt-script.py", line 11, in <module>
    load_entry_point('mbed-greentea==1.2.2', 'console_scripts', 'mbedgt')()
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 389, in main
    cli_ret = main_cli(opts, args)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 662, in main_cli
    test_spec, ret = get_test_spec(opts)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_test_api.py", line 578, in get_test_spec
    elif 'BUILD' in os.listdir():
TypeError: listdir() takes exactly 1 argument (0 given)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-543

**Comment by bridadan** [comment]
Doh! This was my fault, I've submitted a patch here: https://github.com/ARMmbed/greentea/pull/195

Thanks for finding this @jeromecoutant
