### ISSUE TITLE
mbedgt crash with UnicodeDecodeError

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/greentea#240]
Hi

I am sorry, but I still get some crash with the new green tea version ...

mbedgt: exporting to HTML file 'C:/mcu/reports/report__mbed_os5_release_non_regression_F756ZG_mbed-os-5.5.7__2017_09_28_00_06.html'...
mbedgt: unexpected error:
	'unicodeescape' codec can't decode bytes in position 6308-6310: truncated \uXXXX escape
Traceback (most recent call last):
  File "C:\Python27\Scripts\mbedgt-script.py", line 11, in <module>
    load_entry_point('mbed-greentea==1.3.0', 'console_scripts', 'mbedgt')()
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 416, in main
    cli_ret = main_cli(opts, args)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 1067, in main_cli
    html_report = exporter_html(test_report)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_report_api.py", line 747, in exporter_html
    test_results)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_report_api.py", line 636, in get_result_overlay
    overlay_dropdowns = get_result_overlay_dropdowns(result_div_id, test_results)
  File "c:\python27\lib\site-packages\mbed_greentea\mbed_report_api.py", line 598, in get_result_overlay_dropdowns
    .decode("unicode-escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 6308-6310: truncated \uXXXX escape

@theotherjimmy

**Comment by theotherjimmy** [comment]
Could you post the file it's failing to parse?

**Comment by jeromecoutant** [comment]
I don't know which file is parsed...

**Comment by theotherjimmy** [comment]
@jeromecoutant That's okay. I'll make up a test case that covers this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTMORF-1381

**Comment by theotherjimmy** [comment]
This byte string:
```python
  b'\x80abc\uXXXX'
```
is pure evil. I'm going to make it not produce a traceback.

**Comment by theotherjimmy** [comment]
@jeromecoutant Could you see if #243 fixes your issue?

**Comment by jeromecoutant** [comment]
Hi
Could you release it in 1.3.1 version ?
Thx

**Comment by theotherjimmy** [comment]
@jeromecoutant I released 1.3.1 with the fix. Thanks for helping me improve greentea!
