### ISSUE TITLE
greentea to pass additional arguments to htrun

### ISSUE THREAD

**Issue by studavekar** [ARMmbed/greentea#260]
We seeing this failure because program_cycle_s is not been passed to htrun.

Traceback (most recent call last):
  File "/home/arm/jenkins_staging_4_K64F/workspace/tm_wrap/872/htrun/mbed_host_tests/host_tests_runner/host_test_default.py", line 411, in run_test
    callbacks[key](key, value, timestamp)
  File "/home/arm/jenkins_staging_4_K64F/workspace/tm_wrap/872/mbed-os/TESTS/host_tests/watchdog_timing.py", line 116, in cb_heartbeat
    self.heartbeat_timeout_start(MAX_HB_PERIOD + self.get_config_item('program_cycle_s'))
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

**Comment by studavekar** [comment]
closing this issue as changes are merged.
