### ISSUE TITLE
mbedgt --list unexpected error for module with no build directory

### ISSUE THREAD

**Issue by simonqhughes** [ARMmbed/greentea#56]
Hi

Steps to reproduce the problem:
1. git clone git@github.com:ARMmbed/mbed-drivers.git
2. cd mbed-drivers/
3. yt target frdm-k64f-gcc
4. mbedgt --list

This is the output trace of the exception:

simhug01@E107851 /d/datastore/public/jobs/yr2016/2245/work/20160107/mbed-drivers (master)
$ mbedgt --list
←[31m←[1mmbedgt: ←[0munexpected error:
        [Error 3] The system cannot find the path specified: './build/*.*'
Traceback (most recent call last):
  File "c:\mbed_tools\Python27\Scripts\mbedgt-script.py", line 9, in <module>
    load_entry_point('mbed-greentea==0.1.14', 'console_scripts', 'mbedgt')()
  File "C:\mbed_tools\Python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 245, in main
    cli_ret = main_cli(opts, args)
  File "C:\mbed_tools\Python27\lib\site-packages\mbed_greentea\mbed_greentea_cli.py", line 352, in main_cli
    list_binaries_for_targets()
  File "C:\mbed_tools\Python27\lib\site-packages\mbed_greentea\cmake_handlers.py", line 84, in list_binaries_for_targets
    sub_dirs = [os.path.join(dir, o) for o in os.listdir(dir) if os.path.isdir(os.path.join(dir, o))]
WindowsError: [Error 3] The system cannot find the path specified: './build/*.*'
←[0m
simhug01@E107851 /d/datastore/public/jobs/yr2016/2245/work/20160107/mbed-drivers (master)

Thanks
Simon

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-742
