### ISSUE TITLE
[devel_transport] Error when decoding 'socket' test results

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/greentea#87]
```
01:02:17 Traceback (most recent call last):
01:02:17   File "C:\jslv3_2\ws\gtt\venv\Scripts\mbedgt-script.py", line 9, in <module>
01:02:17     load_entry_point('mbed-greentea', 'console_scripts', 'mbedgt')()
01:02:17   File "c:\jslv3_2\ws\gtt\venv\src\mbed-greentea\mbed_greentea\mbed_greentea_cli.py", line 315, in main
01:02:17     cli_ret = main_cli(opts, args)
01:02:17   File "c:\jslv3_2\ws\gtt\venv\src\mbed-greentea\mbed_greentea\mbed_greentea_cli.py", line 842, in main_cli
01:02:17     junit_report = exporter_testcase_junit(test_report, test_suite_properties=yotta_module.get_data())
01:02:17   File "c:\jslv3_2\ws\gtt\venv\src\mbed-greentea\mbed_greentea\mbed_report_api.py", line 203, in exporter_testcase_junit
01:02:17     tc_stderr = test['single_test_output'].decode('unicode_escape').encode('ascii','ignore')
01:02:17 UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 25420-25421: truncated \UXXXXXXXX escape
```

Full console here: http://e108747.cambridge.arm.com:8080/job/gtt/205/console

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2166

**Comment by PrzemekWirkus** [comment]
OK, I've reproduced it on my machine. I will try to apply pach ASAP:
```
mbedgt: checking for GCOV data...
mbedgt: mbed-host-test-runner: stopped
mbedgt: mbed-host-test-runner: returned 'FAIL'
mbedgt: test on hardware with target id: 0240000033514e450041500585d40043e981000097969900
mbedgt: test suite 'socket-test-test-tcp_listener_v0' ................................................ FAIL in 10.88 sec
        test case: 'Test TCPListener destructor method' .............................................. OK in 0.00 sec
        test case: 'Test accept method' .............................................................. FAIL in 0.02 sec
        test case: 'Test start listening method' ..................................................... OK in 0.00 sec
        test case: 'Test stop listening method' ...................................................... OK in 0.01 sec
mbedgt: test case summary: 3 passes, 1 failure
mbedgt: all tests finished!
mbedgt: shuffle seed: 0.8658744074
mbedgt: exporting to JUnit file 'a.xml'...
mbedgt: unexpected error:
        'unicodeescape' codec can't decode bytes in position 25247-25248: truncated \UXXXXXXXX escape
Traceback (most recent call last):
  File "C:\Python27\Scripts\mbedgt-script.py", line 9, in <module>
    load_entry_point('mbed-greentea', 'console_scripts', 'mbedgt')()
  File "c:\work\pypi\greentea\mbed_greentea\mbed_greentea_cli.py", line 320, in main
    cli_ret = main_cli(opts, args)
  File "c:\work\pypi\greentea\mbed_greentea\mbed_greentea_cli.py", line 934, in main_cli
    junit_report = exporter_testcase_junit(test_report, test_suite_properties=yotta_module.get_data())
  File "c:\work\pypi\greentea\mbed_greentea\mbed_report_api.py", line 203, in exporter_testcase_junit
    tc_stderr = test['single_test_output'].decode('unicode_escape').encode('ascii','ignore')
UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position 25247-25248: truncated \UXXXXXXXX escape
```
